[여백 19기 문희원] add : main(home) page get view
wecode-bootcamp-korea/19-1st-whiteSpace-backend pull request #2
Opened 2021-04-16 04:24 UTC by moonimooni

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 페이지 상단 navigation bar와 홈 메인페이지 정보를 response로 보내는 view 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- navigation bar에 들어갈 카테고리 이름, id를 response로 보내는 NavView 작성
- 배너 이미지와 best seller 상품 정보를 reponse로 보내는 MainView 작성
- 프로젝트 디렉토리의 urls.py에서 해당 View들 실행하도록 설정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 상품의 재고를 체크하는 로직을 각 product마다 각 번들옵션의 재고, 칼라사이즈옵션의 재고를 values_list로 받아와서 합치도록 했는데, 이런 방식을 써도 되는건지 궁금합니다...! 만약 안된다면 그 이유도 알 수 있을까요??

'''
for product in best_sellers_qs:
            bundles_stock     = sum(product.bundleoption_set.values_list('stock', flat=True))
            color_sizes_stock = sum(product.colorsizeoption_set.values_list('stock', flat=True))

            product_info = {
                'id' : product.id,
                'name' : product.name,
                'price' : product.price,
                'thumbnail_url' : product.thumbnail_url,
                'stock' : bundles_stock + color_sizes_stock,
                'is_new' : product.is_new
            }
            best_sellers.append(product_info)
'''

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-16 07:27 UTC, ulfrid requested changes
DB_BACKUP은 확인해서 제거해 주시고~, 스톡 관련 코드는 무리없을 것 같습니다. 
예시로 드린 리스트컴프리헨션 코드 참고하셔서 MainView 코드에도 적용해주세요.

2021-04-16 07:27 UTC, ulfrid commented on products/views.py
> +            category_names.append(category_info)
```suggestion
        category_names = [
            {
                'category_id' : category.id,
                'category_name' : category.name
            } for category in Category.objects.all()]
```
가장 파이썬스러운 코드 리스트 컴프리헨션을 사용하면 이렇게 줄여볼 수 있습니다.

2021-04-16 07:31 UTC, moonimooni commented on products/views.py
> +            category_names.append(category_info)
넵! 예시 감사합니다~!!!! 👍🏻

2021-04-17 05:48 UTC, ulfrid requested changes

2021-04-17 05:48 UTC, ulfrid commented on products/views.py
> +            best_sellers.append(product_info)
할수 있을것 같은데 한번더 고민해주세요.

2021-04-17 12:17 UTC, moonimooni commented on products/views.py
> +            best_sellers.append(product_info)
넵! 늦게 확인해서 죄송합니다! 금방 적용시켜서 올리겠습니다~

2021-04-18 02:32 UTC, ulfrid requested changes

2021-04-18 02:32 UTC, ulfrid commented on products/views.py
> +            )
메소드 분리 잘하셨네요. 리스트컴프리헨션까지 적용해주시면 더 좋을 것 같습니다~!
물론 가독성 측면에서는 현재코드가 더 직관적이긴 합니다.
하지만, 성능적인 측면 그리고 보다 파이써닉한 코드라는 측면에서 리스트 컴프리헨션을 권장 드립니다.
두가지 자료를 참고해주세요.
https://umbum.tistory.com/789
https://switowski.com/blog/for-loop-vs-list-comprehension

2021-04-18 05:43 UTC, moonimooni commented on products/views.py
> +            )
호오 차이가 저렇게 나는줄은 몰랐네요,, 좋은 자료 감사합니다!

2021-04-19 01:08 UTC, ulfrid approved these changes
LGTM 👍

2021-04-19 01:08 UTC, merged