[여백 19기 홍태경] Add : Activate SignUp,SignIn
wecode-bootcamp-korea/19-1st-whiteSpace-backend pull request #3
Opened 2021-04-16 11:34 UTC by gusxoqkqh1

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 유저 회원가입 및 로그인 기능 활성화
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입, 로그인 관련 유저앱 뷰 작성 
- 유저 회원가입 관련 정규화, 유저 로그인 관련 데코레이터 관련 Utils 파일 추가 
- 유저 앱의 경로 urls.py Sign-up, Sign-in, Check-email 추가 
-  Check-email 의미 : 회원가입 버튼 활성화 전, 클라이언트 측 메일 중복 체크 버튼 관련
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-17 05:54 UTC, ulfrid requested changes
잘 하셨네요. 수정사항 고치시면 머지 하겠습니다. 다만 PR의 범위가 살짝 큽니다. 펑션 두개 이상 같이 올리지 말아주세요. 덩어리가 큰 기능이라면 메소드 하나당 PR요청 부탁드립니다.

2021-04-17 05:54 UTC, ulfrid commented on users/utils.py
> +            if not User.objects.filter(id=payload['user_id']):
```suggestion
            if not User.objects.filter(id=payload['user_id']).exists():
```
이게 더 정확한 선언이겠죠~

2021-04-17 05:54 UTC, ulfrid commented on users/views.py
> +from .utils       import email_validator, password_validator, phone_validator
임포트 순서
1. 파이썬 모듈

2. 장고 모듈

3. 내가 만든 모듈 및 클래스 

변경해주세요.

2021-04-17 10:33 UTC, gusxoqkqh1 commented on users/views.py
> +from .utils       import email_validator, password_validator, phone_validator
![Selection_024](https://user-images.githubusercontent.com/75156689/115109946-b637ba80-9fb3-11eb-8bb7-f3736de2c3c0.png)

네! 모듈간 구분 확실히 하겠습니다! 주말까지 컴펌 해주셔서 감사합니다!

2021-04-17 10:34 UTC, gusxoqkqh1 commented on users/utils.py
> +            if not User.objects.filter(id=payload['user_id']):
감사합니다!

2021-04-17 10:50 UTC, ulfrid requested changes

2021-04-17 10:50 UTC, ulfrid commented on users/views.py
> +from my_settings  import ALGORITHM, SECRET
```suggestion
from django.views import View
from django.http  import JsonResponse

from .utils       import email_validator, password_validator, phone_validator
from my_settings  import ALGORITHM, SECRET

from .models      import User
```
사용자화 된 모델도~ 구분해주세요

2021-04-17 11:42 UTC, gusxoqkqh1 commented on users/views.py
> +from my_settings  import ALGORITHM, SECRET
멘토님 궁금한 것이 있습니다. .models import User 와 같은 성질을 가진것이 또 무엇이 있나요?
사용화된.. 무언가..? 감이 오지 않습니다 ㅠ

2021-04-18 01:49 UTC, ulfrid commented on users/views.py
> +from my_settings  import ALGORITHM, SECRET
기본 프레임워크에 내장된 Base class를 상속 받아서 만든 클래스는 커스텀 클래스겠죠 이걸 사용자화된 클래스라고 말씀 드린겁니다.

2021-04-18 01:56 UTC, ulfrid requested changes

2021-04-18 01:56 UTC, ulfrid commented on users/views.py
> +class SignUpView(View):
```suggestion
from .models      import User

class SignUpView(View):
```
모든 임포트가 끝난뒤에 클래스 선언을 시작할때에는 두칸을 띄워 주는게 pep8 컨벤션이고,  위코드에서는 한줄 띄어도 무방합니다. 
지속적인 컨벤션 가이드에 지치실 수도 있지만, 협업시에는 이러한 최소한의 규칙이 제일 중요합니다.
컨벤션을 숙지하고 그에 맞게 코딩하는 자세 또한 중요합니다 😀

2021-04-18 02:07 UTC, gusxoqkqh1 commented on users/views.py
> +class SignUpView(View):
네네 컨벤션 확실히 배우겠습니다 신경써주셔서 감사합니다!

2021-04-18 02:34 UTC, ulfrid approved these changes
LGTM 👍

2021-04-18 02:34 UTC, merged