[19기 여백 문희원]Add : Products' list View (get)
wecode-bootcamp-korea/19-1st-whiteSpace-backend pull request #5
Opened 2021-04-19 02:30 UTC by moonimooni

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카테고리별 상품 보여주는 로직 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- category id와 page 번호를 query parameter로 받기로 했습니다.
- 예시 : products?category=3&page=1
- 예시 : products?page=1  << 전체 products 보여줄 때는 category 값을 아예 받지 않도록 프론트와 얘기했습니다!
- 해당 api 주소는 정규표현식으로 처리했습니다.
`re_path(r'^(?:page=(?P<page>\d+))?$', ProductsView.as_view())`
- my_settings에 PAGING_LIMIT 값을 저장해두었습니다. (한 페이지당 보여줄 product 개수 정보)
- 프론트 측에서 해당 카테고리에 속한 상품의(category값이 없다면 전체 상품) 개수 정보를 요청해서 count라는 이름의 key가 추가되었습니다.

## 기타 질문 및 특이 사항
👇 전체 상품 get 결과
![Screen Shot 2021-04-19 at 11 30 19 AM](https://user-images.githubusercontent.com/63729090/115173606-a11d7180-a102-11eb-9f08-3a1566f1d625.png)

👇 특정 category의 상품 get 결과
![Screen Shot 2021-04-19 at 11 30 34 AM](https://user-images.githubusercontent.com/63729090/115173629-aa0e4300-a102-11eb-8915-d4d7db2701de.png)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-19 09:20 UTC, ulfrid requested changes
코드 통해 의도는 잘 전달됐고 확인했습니다. 고생하셨습니다. 수정사항만 확인 해주세요.

2021-04-19 09:20 UTC, ulfrid commented on products/urls.py
> +    re_path(r'^(?:page=(?P<page>\d+))?$', ProductsView.as_view())
정규식을 사용하고 싶어서 해보신 건가요? 아니면 어떤 강제성 때문에? 사실 쿼리 파라미터는 GET을 통해 들어오는 거니까 강제성을 가질 필요는 없습니다.

2021-04-19 09:20 UTC, ulfrid commented on products/views.py
> +            if category_id : category_id = int(category_id)
이건 빼도 괜찮겠네요.

2021-04-19 11:02 UTC, moonimooni commented on products/urls.py
> +    re_path(r'^(?:page=(?P<page>\d+))?$', ProductsView.as_view())
아 원래 저렇게 써야 하는줄 알고 썼습니다 ㅎㅎㅎ 수정하겠습니다!

2021-04-19 11:33 UTC, moonimooni commented on products/views.py
> +            if category_id : category_id = int(category_id)
흠 그럼 이렇게 수정해보겠습니다!

```python
category_id = int(request.GET.get('category', None))
page        = int(request.GET.get('page', None))
```

그래서 아래와 같이 category_id나 page 값이 쓰이는 곳에서
바로바로 쓸 수 있도록 하겠습니다~
```python
if category_id and not Category.objects.filter(id=int(category_id)).exists():
    return JsonResponse({'MESSAGE' : 'INVALID CATEGORY'}, status=404)
```

2021-04-20 02:46 UTC, ulfrid commented on products/views.py
> +            if category_id : category_id = int(category_id)
좋습니다

2021-04-20 02:47 UTC, ulfrid approved these changes
컨플릭트 수정하면 머지 하겠습니다.

2021-04-20 05:22 UTC, merged